#!/usr/bin/env bash
# Version unification script: sync all version numbers from git tag, commit, tag, and build release.
#
# Usage:
#   ./scripts/bump-version.sh              # use latest git tag
#   ./scripts/bump-version.sh v0.2.5       # use specific version
#   ./scripts/bump-version.sh --build-only # skip version bump, just build release
#
# This script ensures all components share the same version:
#   - Git tag (source of truth)
#   - agentapp/pubspec.yaml (Flutter APK/IPA version)
#   - api/cmd/api/main.go (API server version)
#   - agentgw/cmd/agentgw/main.go (Gateway version)
#   - agentd/cmd/agentd/main.go (Agent daemon version)
#   - release manifest.json (auto-generated by release.sh)

set -euo pipefail
cd "$(dirname "$0")/.."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[bump]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[bump]${NC} $*"; }
log_error() { echo -e "${RED}[bump]${NC} $*"; }

# Extract version from git tag (e.g., v0.2.5 → 0.2.5)
get_version_from_tag() {
    local tag="$1"
    echo "${tag#v}"
}

# Get the latest git tag
get_latest_tag() {
    git tag --list 'v*' --sort=-v:refname | head -n1
}

# Validate version format (semver: X.Y.Z)
validate_version() {
    local version="$1"
    if [[ ! "$version" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        log_error "Invalid version format: $version (expected: vX.Y.Z or X.Y.Z)"
        exit 1
    fi
}

# Update pubspec.yaml version
update_pubspec() {
    local version="$1"  # e.g., 0.2.5
    local build_number="$2"  # e.g., 6
    local file="agentapp/pubspec.yaml"
    
    if [[ ! -f "$file" ]]; then
        log_warn "pubspec.yaml not found, skipping"
        return
    fi
    
    log_info "Updating $file → version: ${version}+${build_number}"
    
    # Update version line: version: 0.2.4+5 → version: 0.2.5+6
    sed -i '' "s/^version: .*/version: ${version}+${build_number}/" "$file"
    
    # Verify update
    if grep -q "version: ${version}+${build_number}" "$file"; then
        log_info "  ✓ pubspec.yaml updated"
    else
        log_error "  ✗ Failed to update pubspec.yaml"
        exit 1
    fi
}

# Update Go file version variable
update_go_version() {
    local file="$1"
    local version="$2"  # e.g., v0.2.5
    local component="$3"  # e.g., api, agentgw, agentd
    
    if [[ ! -f "$file" ]]; then
        log_warn "$file not found, skipping"
        return
    fi
    
    log_info "Updating $file → version: $version"
    
    # Update var Version = "vX.Y.Z" or const version = "... vX.Y.Z"
    if grep -q 'var Version = "v' "$file"; then
        sed -i '' "s/var Version = \"v[^\"]*/var Version = \"${version#v}/" "$file"
    elif grep -q 'Version.*=.*"v' "$file"; then
        sed -i '' "s/Version.*=.*\"v[^\"]*/Version = \"${version#v}/" "$file"
    elif grep -q 'const version = ' "$file"; then
        # Handle const version = "agentd v0.1.0"
        sed -i '' "s/const version = \"[^\"]*v[^\"]*/const version = \"${component} ${version#v}/" "$file"
    fi
    
    # Verify update
    if grep -q "${version#v}" "$file"; then
        log_info "  ✓ $file updated"
    else
        log_error "  ✗ Failed to update $file"
        exit 1
    fi
}

# Get current build number from pubspec.yaml and increment
get_next_build_number() {
    local file="agentapp/pubspec.yaml"
    if [[ ! -f "$file" ]]; then
        echo "1"
        return
    fi
    
    local current_build
    current_build=$(grep '^version:' "$file" | sed 's/.*+//' | tr -d ' ')
    if [[ -z "$current_build" || ! "$current_build" =~ ^[0-9]+$ ]]; then
        echo "1"
    else
        echo "$((current_build + 1))"
    fi
}

# Show current versions from all sources
show_current_versions() {
    log_info "Current versions:"
    
    # Git tag
    local tag
    tag=$(get_latest_tag)
    echo "  Git tag:        ${tag:-<none>}"
    
    # pubspec.yaml
    if [[ -f "agentapp/pubspec.yaml" ]]; then
        local pubspec_version
        pubspec_version=$(grep '^version:' agentapp/pubspec.yaml | sed 's/version: //')
        echo "  pubspec.yaml:   $pubspec_version"
    fi
    
    # api/main.go
    if [[ -f "api/cmd/api/main.go" ]]; then
        local api_version
        api_version=$(grep 'Version.*=' api/cmd/api/main.go | grep -o '"v[^"]*"' | tr -d '"')
        echo "  api/main.go:    $api_version"
    fi
    
    # agentgw/main.go
    if [[ -f "agentgw/cmd/agentgw/main.go" ]]; then
        local gw_version
        gw_version=$(grep 'var Version' agentgw/cmd/agentgw/main.go | grep -o '"v[^"]*"' | tr -d '"')
        echo "  agentgw/main:   $gw_version"
    fi
    
    # agentd/main.go
    if [[ -f "agentd/cmd/agentd/main.go" ]]; then
        local ad_version
        ad_version=$(grep 'const version' agentd/cmd/agentd/main.go | grep -o '"[^"]*"' | tr -d '"')
        echo "  agentd/main:    $ad_version"
    fi
}

# Main
main() {
    local version=""
    local build_only=false
    local skip_build=false
    
    # Parse arguments
    for arg in "$@"; do
        case "$arg" in
            --build-only)
                build_only=true
                ;;
            --skip-build)
                skip_build=true
                ;;
            -h|--help)
                cat <<'EOF'
Usage: ./scripts/bump-version.sh [OPTIONS] [VERSION]

Sync all version numbers from a single source (git tag or explicit version),
commit changes, create git tag, and build release.

OPTIONS:
  --build-only    Skip version bump, just build release from current state
  --skip-build    Bump versions and create tag, but don't build release
  -h, --help      Show this help message

ARGUMENTS:
  VERSION         Target version (e.g., v0.2.5). If omitted, uses latest git tag.

EXAMPLES:
  # Use latest git tag
  ./scripts/bump-version.sh

  # Use specific version
  ./scripts/bump-version.sh v0.2.5

  # Just build without version changes
  ./scripts/bump-version.sh --build-only

EOF
                exit 0
                ;;
            v*)
                version="$arg"
                ;;
            [0-9]*)
                version="v$arg"
                ;;
        esac
    done
    
    if $build_only; then
        log_info "Build-only mode: skipping version bump"
        log_info "Running release.sh..."
        exec bash scripts/release.sh "$@"
    fi
    
    # Show current state
    show_current_versions
    echo
    
    # Determine target version
    if [[ -z "$version" ]]; then
        version=$(get_latest_tag)
        if [[ -z "$version" ]]; then
            log_error "No git tag found. Please create one first:"
            log_error "  git tag v0.2.5"
            log_error "Or provide version explicitly:"
            log_error "  ./scripts/bump-version.sh v0.2.5"
            exit 1
        fi
        log_info "Using latest git tag: $version"
    else
        validate_version "$version"
        log_info "Using specified version: $version"
    fi
    
    # Normalize version (remove v prefix for pubspec, keep for Go)
    local semver="${version#v}"  # e.g., 0.2.5
    local build_number
    build_number=$(get_next_build_number)
    
    log_info "Target: $version (semver: $semver, build: $build_number)"
    echo
    
    # Check for uncommitted changes
    if ! git diff-index --quiet HEAD --; then
        log_warn "You have uncommitted changes. Commit them first or stash them."
        git status --short
        read -rp "Continue anyway? [y/N] " confirm
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            exit 1
        fi
    fi
    
    # Update all version files
    log_info "Updating version files..."
    update_pubspec "$semver" "$build_number"
    update_go_version "api/cmd/api/main.go" "$version" "api"
    update_go_version "agentgw/cmd/agentgw/main.go" "$version" "agentgw"
    update_go_version "agentd/cmd/agentd/main.go" "$version" "agentd"
    
    echo
    log_info "Updated versions:"
    show_current_versions
    echo
    
    # Stage changes
    log_info "Staging version changes..."
    git add agentapp/pubspec.yaml api/cmd/api/main.go agentgw/cmd/agentgw/main.go agentd/cmd/agentd/main.go
    
    # Commit
    log_info "Creating commit..."
    git commit -m "chore: bump version to ${version}

Synchronize version across all components:
- agentapp (pubspec.yaml): ${semver}+${build_number}
- api: ${version}
- agentgw: ${version}
- agentd: ${version}"
    
    # Create git tag if it doesn't exist
    if ! git tag --list "$version" | grep -q "$version"; then
        log_info "Creating git tag: $version"
        git tag -a "$version" -m "Release ${version}"
    else
        log_warn "Tag $version already exists, skipping tag creation"
    fi
    
    echo
    log_info "Version bump complete!"
    log_info "  Commit: $(git rev-parse --short HEAD)"
    log_info "  Tag:    $version"
    echo
    
    # Build release
    if ! $skip_build; then
        log_info "Building release..."
        bash scripts/release.sh "$@"
    else
        log_info "Skipping build (--skip-build)"
    fi
    
    echo
    log_info "Done! Next steps:"
    log_info "  git push origin main"
    log_info "  git push origin $version"
}

main "$@"
